---

- name: scale down asb deploymentconfig
  oc_obj: TODO

- name: Run asb pod with migration arguments
  oc_obj:
    name: asb_migration
    namespace: openshift-ansible-service-broker
    kind: Job
    state: present
    content:
      path: /tmp/asb_migrate_out
      data:
        apiVersion: v1
        kind: Job
        metadata:
          name: asb-etcd-migration
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              name: asb-etcd-migration
            spec:
              containers:
                - name: asb
                  image: '{{ ansible_service_broker_image }}'
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                    - name: config-volume
                      mountPath: /etc/ansible-service-broker
                    - name: asb-tls
                      mountPath: /etc/tls/private
                    - name: asb-etcd-auth
                      mountPath: /var/run/asb-etcd-auth
                  env:
                    - name: BROKER_CONFIG
                      value: /etc/ansible-service-broker/config.yaml
                    - name: HTTP_PROXY
                      value: "{{ openshift.common.http_proxy  | default('') }}"
                    - name: HTTPS_PROXY
                      value: "{{ openshift.common.https_proxy  | default('') }}"
                    - name: NO_PROXY
                      value: "{{ ([openshift.common.no_proxy, '.default'] | join(',')) if openshift.get('common', {}).get('no_proxy') else '' }}"
              volumes:
                - name: config-volume
                  configMap:
                    name: broker-config
                    items:
                      - key: broker-config
                        path: config.yaml
                - name: asb-tls
                  secret:
                    secretName: asb-tls
                - name: asb-etcd-auth
                  secret:
                    secretName: broker-etcd-auth-secret
              restartPolicy: Never
- name: wait for migration to complete
  oc_obj:
    namespace: openshift-ansible-service-broker
    kind: job
    state: list
    name: asb-etcd-migration
  register: migration_status
  until:
    - TODO: need to find out what this looks like on termination

- when: not (migrate_status|failed)  # TODO
  block:
    - name: delete etcd service
      oc_service:
        name: asb-etcd
        namespace: openshift-ansible-service-broker
        state: absent

    - name: delete etcd deploymentconfig
      oc_obj:
        name: asb-etcd
        namespace: openshift-ansible-service-broker
        kind: DeploymentConfig
        state: absent

    - name: delete etcd secrets
      oc_secret:
        name: '{{ item }}'
        namespace: openshift_ansible_service_broker
        state: absent
      with_items:
        - etcd-auth-secret
        - broker-etcd-auth-secret
